all: a3p3Client1 a3p3Client2 a3p3Client3 a3p3Server

a3p3Client1: a3p3Client1.c
	gcc -o a3p3Client1 a3p3Client1.c

a3p3Client2: a3p3Client2.c
	gcc -o a3p3Client2 a3p3Client2.c

a3p3Client3: a3p3Client3.c
	gcc -o a3p3Client3 a3p3Client3.c

a3p3Server: a3p3Server.c
	gcc -o a3p3Server a3p3Server.c

